### ISSUE TITLE
Kira Audio

### ISSUE THREAD

**Issue by IllustrisJack** [Limit-Theory-Redux/ltheory#149]
```[tasklist]
### Tasks
- [ ] https://github.com/Limit-Theory-Redux/ltheory/issues/128
- [ ] https://github.com/Limit-Theory-Redux/ltheory/issues/115
- [ ] Investigate Audio.Create = nil error in Tests
```

**Comment by IllustrisJack** [comment]
I added it as an issue so we don´t forget it. Also the Tasklist is nice to see what has to be done. @HaronK
