### ISSUE TITLE
[Tasklist] Economy

### ISSUE THREAD

**Issue by IllustrisJack** [Limit-Theory-Redux/ltheory#222]
```[tasklist]
### Tasks
- [ ] Station construction
- [ ] Tax
- [ ] Station delivery job (deliver blueprint to new station position)
- [ ] Station construction job
- [ ] AI Strategic Focus: Economy
```

#214
