### ISSUE TITLE
Entity Component System

### ISSUE THREAD

**Issue by IllustrisJack** [Limit-Theory-Redux/ltheory#324]
```[tasklist]
### ECS Structure
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Milestone: Functional Rendering
- [ ] Material/Texture/AutoShaderVar working, and fully tested
- [ ] Rendering System Running on 'Render' event
- [ ] Camera
- [ ] renderState
- [ ] Material Generation for Asteroid
- [ ] RenderComponent
```

**Comment by IllustrisJack** [comment]
https://github.com/Limit-Theory-Redux/ltheory/pull/359
