### ISSUE TITLE
[Tasklist] First Iteration of Factions Tasklist

### ISSUE THREAD

**Issue by IllustrisJack** [Limit-Theory-Redux/ltheory#87]
```[tasklist]
### Tasks
- [x] Allow Faction Entities
- [x] Allow Player Faction
- [x] Assets should also be part of the faction of the owner
- [x] UI color for player faction ships
- [ ] Move full economy jobs to faction jobs
- [x] Allow faction claims
- [ ] Allow faction claim desires
- [ ] Allow faction dynamic relations
- [x] Allow faction subordinates
```

**Comment by IllustrisJack** [comment]
If someone wants to support the effort contribute to https://github.com/Limit-Theory-Redux/ltheory/tree/feature/factions

**Comment by IllustrisJack** [comment]
Will be rewritten in ECS
