### ISSUE TITLE
Modernize the new Rust codebase

### ISSUE THREAD

**Issue by dgavedissian** [Limit-Theory-Redux/ltheory#93]
Now that we've merged the first pass of the Rust converted codebase, there are a few ways we can begin refactoring and improving it:

```[tasklist]
### Tasks
- [ ] Replace the raw C string handling with Rust strings - in particular in the Shader parsing code. The end goal would be to delete all the functions beginning with `Str` i.e. `StrDup` in `libphx/src/internal/Memory.rs`
- [ ] Go through all the Rust source files from `Joystick.rs` to `WindowPos.rs`, and compare them side by side with the equivalent cpp files and make sure missing comments/formatting are copied across. You'll need to check out an earlier commit of the ltheory repo to see the original `.cpp` files.
- [ ] Replace all remaining usage of `MemAlloc`/`MemFree` with `Box<T>`, using `Window.rs` as an example of how to use `Box` safely across C FFI boundaries
```
